name: barry-prx
channels:
  - conda-forge
  - pysces
dependencies:
  - python=3.10
  - numpy
  - assimulo
  - pysces>=1.1.1
  - pandas
  - scikit-learn
  - notebook
  - lmfit
  - ipython
  - ipywidgets
  - dill
  - sortedcontainers
